### ISSUE TITLE
Added lying face emoji

### ISSUE THREAD

**Issue by Limaeoha** [emojidex/wp-emojidex-tinymce-plugin#2]
This is not smileys in:                                                                                                                
![lying-face_1f925](https://user-images.githubusercontent.com/90700465/133433573-7d357678-687b-4c50-9f26-82af8a2df944.png)

**Comment by Limaeoha** [comment]
Thank you for emojis!

**Comment by Limaeoha** [comment]
GitHub here:                                                                                                                                         https://github.com/jaybon1/PhantomOpenEmoji/design/category/                                                                                           https://github.com/jaybon1/PhantomOpenEmoji

**Comment by Kagetsuki** [comment]
This is not the place to "add" emoji. You can do so on emojidex.com . This is a plugin for the TinyMCE editor.

**Comment by Limaeoha** [comment]
https://github.com/jaybon1/PhantomOpenEmoji

**Comment by Limaeoha** [comment]
https://github.com/jaybon1/PhantomOpenEmoji/design/created
